import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core"; 
import "@copilotkit/react-ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const CLIENT_JWT = "eyJhbGciOiJIUzI1NiIsImtpZCI6ImJwV1R6aXhqclJxMXhBV2wiLCJ0eXAiOiJKV1QifQ.eyJhYWwiOiJhYWwxIiwiYXVkIjoiYXV0aGVudGljYXRlZCIsImVtYWlsIjoiY2FuY2lub2QwODBAZ21haWwuY29tIiwiZXhwIjoxNzYzNzU5NTI1LCJpYXQiOjE3NjM3NTU5MjUsImlzX2Fub255bW91cyI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYWdtaXZtdHB0d2hhc3RraHRjeG0uc3VwYWJhc2UuY28vYXV0aC92MSIsIm9yZ2FuaXphdGlvbiI6eyJpZCI6Ijg1NTU1MDUzLTUwYzUtNDMxMi04N2FhLTgxZmYzMjEzZTc1OSIsIm5hbWUiOiJUZWdtYSBTb2x1dGlvbnMifSwicGhvbmUiOiIiLCJwcm9maWxlX2lkIjoiN2JhYTE1NDEtMDZjNS00ZDUyLTk2M2YtODQ3YTZiMjYxNDhjIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJyb2xlLWFwcCI6ImFkbWluX29yZyIsInNjb3BlcyI6WyJwcm9maWxlczpjcmVhdGUiLCJwcm9maWxlczpyZWFkIiwicHJvZmlsZXM6ZGVsZXRlIiwib3JnYW5pemF0aW9uOnJlYWRcbiIsIm9yZ2FuaXphdGlvbjp1cGRhdGUiLCJpbnZpdGF0aW9uczpjcmVhdGUiLCJpbnZpdGF0aW9uczpyZWFkIiwiaW52aXRhdGlvbnM6ZGVsZXRlIl0sInNlc3Npb25faWQiOiIxMDI1YmM0ZC1iNWI0LTQyMTQtOGU4OC0zYzAzOGU4ZjZiNmMiLCJzdWIiOiJmZGY5MTlkMy04OTJkLTQyMmUtYjc0My1iZWNlYzc1MzhmYjkifQ.0F28TokR2wlBx9OzZjntxPUUi4WBmPeTSHJK1BKx6tU"

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <CopilotKit
          threadId="cc22f2eb-8d89-402a-b51b-44dc20c47a0a" 
          runtimeUrl="/api/copilotkit"
          publicApiKey={process.env.NEXT_PUBLIC_CPK_PUBLIC_API_KEY}
          agent="fast_assistant_sale"
          headers={{authorization : `Bearer ${CLIENT_JWT}`}}
          >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}


