import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core"; 
import "@copilotkit/react-ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const CLIENT_JWT = "eyJhbGciOiJIUzI1NiIsImtpZCI6ImJwV1R6aXhqclJxMXhBV2wiLCJ0eXAiOiJKV1QifQ.eyJhYWwiOiJhYWwxIiwiYXVkIjoiYXV0aGVudGljYXRlZCIsImVtYWlsIjoiY2FuY2lub2QwODBAZ21haWwuY29tIiwiZXhwIjoxNzYzNTAyNDc5LCJpYXQiOjE3NjM0OTg4NzksImlzX2Fub255bW91cyI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYWdtaXZtdHB0d2hhc3RraHRjeG0uc3VwYWJhc2UuY28vYXV0aC92MSIsIm9yZ2FuaXphdGlvbiI6eyJpZCI6Ijg1NTU1MDUzLTUwYzUtNDMxMi04N2FhLTgxZmYzMjEzZTc1OSIsIm5hbWUiOiJUZWdtYSBTb2x1dGlvbnMifSwicGhvbmUiOiIiLCJwcm9maWxlX2lkIjoiN2JhYTE1NDEtMDZjNS00ZDUyLTk2M2YtODQ3YTZiMjYxNDhjIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJyb2xlLWFwcCI6ImFkbWluX29yZyIsInNjb3BlcyI6WyJwcm9maWxlczpjcmVhdGUiLCJwcm9maWxlczpyZWFkIiwicHJvZmlsZXM6ZGVsZXRlIiwib3JnYW5pemF0aW9uOnJlYWRcbiIsIm9yZ2FuaXphdGlvbjp1cGRhdGUiLCJpbnZpdGF0aW9uczpjcmVhdGUiLCJpbnZpdGF0aW9uczpyZWFkIiwiaW52aXRhdGlvbnM6ZGVsZXRlIl0sInNlc3Npb25faWQiOiIyMzg3ZDJmMS1lYWY4LTQxZmQtYmIzMC04YmMyNzI3MDYwMjEiLCJzdWIiOiJmZGY5MTlkMy04OTJkLTQyMmUtYjc0My1iZWNlYzc1MzhmYjkifQ.uIGJBypELYbtW5XCJFeG98Lc3CGKcajmY7pO8q8Kxm0"

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <CopilotKit
          threadId="915ecfde-d102-4615-b557-ec02b982dedd" 
          runtimeUrl="/api/copilotkit"
          publicApiKey={process.env.NEXT_PUBLIC_CPK_PUBLIC_API_KEY}
          agent="prodmentor_workflow"
          headers={{
            Authorization: `Bearer ${CLIENT_JWT}`
          }}
          >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}


